"""
SUDA Compiler — NMC4 Kernel Code Generator for PromeTorch
==========================================================
Generates optimized NMC4 assembly (.asm) and C++ dispatcher code
for ML operations on NeuroMatrix vector pipeline.

Usage:
    python suda/codegen.py --op matmul --output dispatcher_suda.cpp
    python suda/codegen.py --op all --output dispatcher_suda.cpp

The generated code links with:
  - libnmpps-nmc4.a (vectorized matmul via 4 FPU cores)
  - libgcc_float.a (IEEE 754 float support)

NMC4 Vector Pipeline ISA (from MullMatrix_f.asm analysis):
  fpu N rep vlen vreg = [arX++grX]           # vector load with stride
  fpu N .matrix vreg = vregA * .retrive(vregB, vregC)           # matrix FMA
  fpu N .matrix vreg = vregA * .retrive(vregB, vregC) + vregD   # matrix FMA+acc
  fpu N vregX = fpu M vregX                  # inter-FPU data transfer
  vlen = grN                                 # set vector length
  rep N <instruction>                        # repeat N times (no branch overhead)
"""

import argparse
import os
import sys
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class KernelSpec:
    """Specification for an NMC4 kernel."""
    name: str           # Operation name
    opcode: int         # Dispatcher opcode
    args: List[str]     # Argument names from mem[] words
    use_nmpp: bool      # Use nmpp vectorized library
    nmpp_func: str      # nmpp function name (if use_nmpp)
    body_scalar: str    # Scalar C fallback body


# ============================================================================
# NMC4 ISA Templates
# ============================================================================

ASM_HEADER = """\
; ============================================================
; {name}.asm — SUDA-generated NMC4 kernel for {desc}
; Generated by PromeTorch SUDA Compiler
; Target: NMC4 NeuroMatrix (K1879VM8YA)
; Vector pipeline: 4 FPU cores, rep vlen, .matrix mode
; ============================================================

global _{name} : label;

begin ".text_suda"

<_{name}>
    push ar6, gr6;
    ar6 = ar7;
    push ar0, gr0;
    push ar1, gr1;
    push ar2, gr2;
"""

ASM_FOOTER = """\
    pop ar2, gr2;
    pop ar1, gr1;
    pop ar0, gr0;
    pop ar6, gr6;
    return;

end ".text_suda"
"""

ASM_VECTOR_LOAD = """\
    ; Load {count} elements from [{src_reg}] with stride {stride_reg}
    fpu {fpu_id}  rep vlen  vreg{dst} = [{src_reg}++{stride_reg}];
"""

ASM_MATRIX_FMA = """\
    ; Matrix FMA: vreg{dst} = vreg{a} * .retrive(vreg{b0}, vreg{b1}) {acc}
    fpu {fpu_id}  .matrix  vreg{dst} = vreg{a} * .retrive(vreg{b0}, vreg{b1}){acc_str};
"""

ASM_INTER_FPU = """\
    ; Transfer vreg{reg} from fpu {src} to fpu {dst}
    fpu {dst}  vreg{reg} = fpu {src} vreg{reg};
"""


# ============================================================================
# Kernel Definitions
# ============================================================================

KERNELS = {
    'matmul': KernelSpec(
        name='suda_matmul',
        opcode=1,
        args=['M', 'K', 'N', 'addr_A', 'addr_B', 'addr_C'],
        use_nmpp=True,
        nmpp_func='nmppmMul_mm_32f',
        body_scalar="""\
    int M=(int)mem[1]; int K=(int)mem[2]; int N=(int)mem[3];
    float* A=(float*)mem[4]; float* B=(float*)mem[5]; float* C=(float*)mem[6];
    nmppmMul_mm_32f(A, M, K, B, K, N, C, N, N, 0);"""
    ),

    'matmul_at': KernelSpec(
        name='suda_matmul_at',
        opcode=2,
        args=['M', 'K', 'N', 'addr_A', 'addr_B', 'addr_C'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int k=0;k<K;k++)
        for(unsigned int n=0;n<N;n++){
            float s=0.0f;
            for(unsigned int i=0;i<M;i++) s+=A[i*K+k]*B[i*N+n];
            C[ci++]=s;
        }"""
    ),

    'matmul_bt': KernelSpec(
        name='suda_matmul_bt',
        opcode=3,
        args=['M', 'K', 'N', 'addr_A', 'addr_B', 'addr_C'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int m=0;m<M;m++)
        for(unsigned int k=0;k<K;k++){
            float s=0.0f;
            for(unsigned int n=0;n<N;n++) s+=A[m*N+n]*B[k*N+n];
            C[ci++]=s;
        }"""
    ),

    'relu': KernelSpec(
        name='suda_relu',
        opcode=4,
        args=['count', 'addr_in', 'addr_out'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int n=mem[1]; float*x=(float*)mem[2]; float*y=(float*)mem[3];
    for(unsigned int i=0;i<n;i++) y[i]=x[i]>0.0f?x[i]:0.0f;"""
    ),

    'relu_bwd': KernelSpec(
        name='suda_relu_bwd',
        opcode=5,
        args=['count', 'addr_dy', 'addr_x', 'addr_dx'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int n=mem[1]; float*dy=(float*)mem[2]; float*x=(float*)mem[3]; float*dx=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) dx[i]=x[i]>0.0f?dy[i]:0.0f;"""
    ),

    'elem_add': KernelSpec(
        name='suda_elem_add',
        opcode=10,
        args=['count', 'addr_a', 'addr_b', 'addr_out'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int n=mem[1]; float*a=(float*)mem[2]; float*b=(float*)mem[3]; float*o=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) o[i]=a[i]+b[i];"""
    ),

    'sgd': KernelSpec(
        name='suda_sgd',
        opcode=20,
        args=['count', 'addr_w', 'addr_g', 'lr_bits'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int n=mem[1]; float*w=(float*)mem[2]; float*g=(float*)mem[3];
    unsigned int lr_u=mem[4]; float*lr_p=(float*)&lr_u; float lr=*lr_p;
    for(unsigned int i=0;i<n;i++) w[i]-=lr*g[i];"""
    ),

    'softmax': KernelSpec(
        name='suda_softmax',
        opcode=7,
        args=['batch', 'dim', 'addr_in', 'addr_out'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int batch=mem[1], dim=mem[2];
    float*in=(float*)mem[3]; float*out=(float*)mem[4];
    for(unsigned int b=0;b<batch;b++){
        float*x=in+b*dim; float*y=out+b*dim;
        float mx=x[0];
        for(unsigned int i=1;i<dim;i++) if(x[i]>mx) mx=x[i];
        float s=0.0f;
        for(unsigned int i=0;i<dim;i++){
            float diff=x[i]-mx; if(diff<-10.0f) diff=-10.0f;
            float e=1.0f+diff+diff*diff*0.5f+diff*diff*diff*0.16667f+diff*diff*diff*diff*0.04167f;
            if(e<0.0f) e=0.0f; y[i]=e; s+=e;
        }
        if(s>0.0f){float is=1.0f/s; for(unsigned int i=0;i<dim;i++) y[i]*=is;}
    }"""
    ),

    'rmsnorm': KernelSpec(
        name='suda_rmsnorm',
        opcode=6,
        args=['T', 'D', 'addr_x', 'addr_gamma', 'addr_y'],
        use_nmpp=False,
        nmpp_func='',
        body_scalar="""\
    unsigned int T=mem[1], D=mem[2];
    float*x=(float*)mem[3]; float*g=(float*)mem[4]; float*y=(float*)mem[5];
    for(unsigned int t=0;t<T;t++){
        float*xr=x+t*D; float*yr=y+t*D; float ss=0.0f;
        for(unsigned int d=0;d<D;d++) ss+=xr[d]*xr[d];
        float inv=1.0f, rms2=ss/(float)D+1e-6f;
        if(rms2*0.5f>0.0f){
            float x0=1.0f;
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            inv=x0;
        }
        for(unsigned int d=0;d<D;d++) yr[d]=xr[d]*inv*g[d];
    }"""
    ),
}


# ============================================================================
# C++ Dispatcher Generator
# ============================================================================

def generate_dispatcher_cpp(ops: List[str], multicore: bool = False) -> str:
    """Generate complete dispatcher C++ source with nmpp linkage."""

    lines = []
    lines.append('// ============================================================')
    lines.append('// SUDA-Generated Dispatcher for NMC4 NeuroMatrix')
    lines.append('// Generated by: python suda/codegen.py')
    lines.append('// Vector matmul: nmppmMul_mm_32f (4 FPU cores, rep vlen)')
    lines.append('// ============================================================')
    lines.append('')

    # nmpp declarations
    has_nmpp = any(KERNELS[op].use_nmpp for op in ops)
    if has_nmpp:
        lines.append('extern "C" {')
        lines.append('    void nmppmMul_mm_32f(float* pSrcMtr1, int nHeight1, int nStride1,')
        lines.append('                          float* pSrcMtr2, int nWidth1, int nStride2,')
        lines.append('                          float* pDstMtr, int nWidth2, int nStrideDst, int bPlusDst);')
        lines.append('}')
        lines.append('')

    lines.append('#define DDR_BASE 0x00340000')

    if multicore:
        lines.append('#define CMD_BLOCK_SIZE 32')
        lines.append('volatile unsigned int* mem;')
    else:
        lines.append('volatile unsigned int* mem = (volatile unsigned int*)DDR_BASE;')

    lines.append('')

    # Opcodes
    for op_name in ops:
        k = KERNELS[op_name]
        lines.append(f'#define OP_{op_name.upper():20s} {k.opcode}')
    lines.append(f'#define OP_{"NOP":20s} 0')
    lines.append(f'#define OP_{"EXIT":20s} 255')
    lines.append(f'#define STATUS_ADDR     30')
    lines.append(f'#define WATCHDOG_ADDR   31')
    lines.append('')

    # Operation functions
    for op_name in ops:
        k = KERNELS[op_name]
        lines.append(f'// {op_name}: args [{", ".join(k.args)}]')
        if k.use_nmpp:
            lines.append(f'// VECTORIZED via nmpp ({k.nmpp_func})')
        lines.append(f'void op_{op_name}() {{')
        lines.append(k.body_scalar)
        lines.append('}')
        lines.append('')

    # Main dispatcher loop
    if multicore:
        lines.append('// Stubs for libnm6408load_nmc')
        lines.append('extern "C" unsigned int LShift32(unsigned int a, unsigned int b) {')
        lines.append('    unsigned int r=a; for(unsigned int i=0;i<b;i++) r<<=1; return r; }')
        lines.append('extern "C" unsigned int RShift32(unsigned int a, unsigned int b) {')
        lines.append('    unsigned int r=a; for(unsigned int i=0;i<b;i++) r>>=1; return r; }')
        lines.append('extern "C" int Mul32(int a, int b) {')
        lines.append('    int r=0,s=1; if(a<0){a=-a;s=-s;} if(b<0){b=-b;s=-s;}')
        lines.append('    unsigned int ua=(unsigned int)a,ub=(unsigned int)b;')
        lines.append('    while(ub){if(ub&1)r+=ua;ua<<=1;ub>>=1;} return s<0?-r:r; }')
        lines.append('')
        lines.append('int main() {')
        lines.append('    volatile unsigned int* boot=(volatile unsigned int*)DDR_BASE;')
        lines.append('    unsigned int core_index=boot[29];')
        lines.append('    if(core_index>15) core_index=0;')
        lines.append('    mem=(volatile unsigned int*)(DDR_BASE+(core_index<<5));')
    else:
        lines.append('int main() {')

    lines.append('    mem[STATUS_ADDR]=1; mem[WATCHDOG_ADDR]=0; mem[0]=0;')
    lines.append('    unsigned int watchdog=0;')
    lines.append('    while(1){')
    lines.append('        watchdog++; mem[WATCHDOG_ADDR]=watchdog;')
    lines.append('        unsigned int op=mem[0];')
    lines.append('        if(op==OP_NOP) continue;')
    lines.append('        if(op==OP_EXIT){mem[STATUS_ADDR]=1;mem[0]=0;break;}')
    lines.append('        mem[STATUS_ADDR]=0;')
    lines.append('        switch(op){')
    for op_name in ops:
        k = KERNELS[op_name]
        tag = ' /*VEC*/' if k.use_nmpp else ''
        lines.append(f'            case OP_{op_name.upper()}: op_{op_name}(); break;{tag}')
    lines.append('            default: mem[STATUS_ADDR]=2; mem[0]=0; continue;')
    lines.append('        }')
    lines.append('        mem[STATUS_ADDR]=1; mem[0]=0;')
    lines.append('    }')
    lines.append('    return 0;')
    lines.append('}')

    return '\n'.join(lines) + '\n'


def generate_build_script(name: str, has_nmpp: bool, multicore: bool) -> str:
    """Generate build.bat for the dispatcher."""
    lines = []
    lines.append('@echo off')
    lines.append('set NMC_GCC_TOOLPATH=C:\\Program Files\\Module\\NMC-SDK')
    lines.append('set IDE=%NMC_GCC_TOOLPATH%\\nmc4-ide')
    lines.append('set CC1PLUS=%IDE%\\libexec\\gcc\\nmc\\4.8.3\\cc1plus.exe')
    lines.append('set AS_GNU=%IDE%\\bin\\nmc-as-gnu.exe')
    lines.append('set LD=%IDE%\\bin\\nmc-ld.exe')
    lines.append('set LIBGCC_FLOAT=%IDE%\\lib\\gcc\\nmc\\4.8.3\\nmc4-float\\libgcc.a')
    lines.append('')
    lines.append(f'echo Building {name}.abs (SUDA generated)...')
    lines.append(f'"%CC1PLUS%" -quiet {name}.cpp -mnmc4 -mgas -O2 -o {name}_gas.s')
    lines.append(f'"%AS_GNU%" -o {name}_gas.o {name}_gas.s')

    link_objs = f'nmc_startup.o {name}_gas.o'
    if has_nmpp:
        link_objs += ' MullMatrix_f.o TmpBuffers64G.o'
    link_objs += ' "%LIBGCC_FLOAT%"'

    lines.append(f'"%LD%" -o {name}.abs {link_objs} -T nm6408brd.lds -e start')
    lines.append(f'if exist {name}.abs (')
    lines.append(f'    echo [OK] {name}.abs')
    lines.append(f'    del {name}_gas.s {name}_gas.o 2>nul')
    lines.append(') else (')
    lines.append(f'    echo [FAIL] Build failed')
    lines.append(')')
    return '\n'.join(lines) + '\n'


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description='SUDA Compiler — NMC4 Kernel Code Generator')
    parser.add_argument('--op', default='all', help='Operation to generate (or "all")')
    parser.add_argument('--output', default='dispatcher_suda.cpp', help='Output C++ file')
    parser.add_argument('--multicore', action='store_true', help='Generate 16-core dispatcher')
    parser.add_argument('--build-script', default=None, help='Generate build.bat')
    parser.add_argument('--list-ops', action='store_true', help='List available operations')
    args = parser.parse_args()

    if args.list_ops:
        print('Available SUDA operations:')
        for name, spec in KERNELS.items():
            vec = ' [VECTORIZED nmpp]' if spec.use_nmpp else ''
            print(f'  {name:15s} opcode={spec.opcode:3d}  args={spec.args}{vec}')
        return

    if args.op == 'all':
        ops = list(KERNELS.keys())
    else:
        ops = [o.strip() for o in args.op.split(',')]
        for op in ops:
            if op not in KERNELS:
                print(f'ERROR: Unknown operation "{op}". Use --list-ops to see available.')
                sys.exit(1)

    # Generate C++
    cpp = generate_dispatcher_cpp(ops, multicore=args.multicore)

    output_path = args.output
    if not os.path.isabs(output_path):
        output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    '..', 'aten', 'src', 'ATen', 'nmcard', 'nmc_programs',
                                    output_path)

    with open(output_path, 'w') as f:
        f.write(cpp)

    has_nmpp = any(KERNELS[op].use_nmpp for op in ops)
    name = os.path.splitext(os.path.basename(args.output))[0]
    print(f'SUDA: Generated {output_path}')
    print(f'  Operations: {", ".join(ops)}')
    print(f'  Vectorized (nmpp): {", ".join(o for o in ops if KERNELS[o].use_nmpp) or "none"}')
    print(f'  Multicore: {args.multicore}')

    # Generate build script
    build_path = args.build_script
    if build_path is None:
        build_path = os.path.join(os.path.dirname(output_path), f'build_{name}.bat')
    with open(build_path, 'w') as f:
        f.write(generate_build_script(name, has_nmpp, args.multicore))
    print(f'  Build script: {build_path}')

    print(f'\nTo compile:')
    print(f'  cd aten/src/ATen/nmcard/nmc_programs')
    print(f'  build_{name}.bat')


if __name__ == '__main__':
    main()
