FROM centos:8 AS redos-build
RUN dnf group install -y "Development Tools" && dnf install -y cmake && dnf clean all
WORKDIR /opt/promethorch
COPY . .
RUN mkdir build_redos && cd build_redos && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
    -DPT_USE_TUDA=ON -DPT_USE_LINQ=OFF -DPT_USE_CUDA=OFF \
    -DPT_BUILD_TESTS=ON -DPT_BUILD_SHARED_LIBS=ON && \
    cmake --build . -j$(nproc)
RUN cd build_redos && ./tuda_tests
