// ============================================================
// SUDA-Generated Dispatcher for NMC4 NeuroMatrix
// Generated by: python suda/codegen.py
// Vector matmul: nmppmMul_mm_32f (4 FPU cores, rep vlen)
// ============================================================

extern "C" {
    void nmppmMul_mm_32f(float* pSrcMtr1, int nHeight1, int nStride1,
                          float* pSrcMtr2, int nWidth1, int nStride2,
                          float* pDstMtr, int nWidth2, int nStrideDst, int bPlusDst);
}

#define DDR_BASE 0x00340000
#define CMD_BLOCK_SIZE 32
volatile unsigned int* mem;

// FIX C11: Global core index, validated at startup to prevent race condition
// where multiple cores read same boot[29] value from shared DDR
unsigned int g_core_index = 0;

#define OP_MATMUL               1
#define OP_MATMUL_AT            2
#define OP_MATMUL_BT            3
#define OP_RELU                 4
#define OP_RELU_BWD             5
#define OP_ELEM_ADD             10
#define OP_SGD                  20
#define OP_SOFTMAX              7
#define OP_RMSNORM              6
#define OP_MATMUL_PARTIAL       22
#define OP_NOP                  0
#define OP_EXIT                 255
#define STATUS_ADDR     30
#define WATCHDOG_ADDR   31

// matmul: args [M, K, N, addr_A, addr_B, addr_C]
// VECTORIZED via nmpp (nmppmMul_mm_32f)
void op_matmul() {
    int M=(int)mem[1]; int K=(int)mem[2]; int N=(int)mem[3];
    float* A=(float*)mem[4]; float* B=(float*)mem[5]; float* C=(float*)mem[6];
    nmppmMul_mm_32f(A, M, K, B, K, N, C, N, N, 0);
}

// matmul_at: args [M, K, N, addr_A, addr_B, addr_C]
void op_matmul_at() {
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int k=0;k<K;k++)
        for(unsigned int n=0;n<N;n++){
            float s=0.0f;
            for(unsigned int i=0;i<M;i++) s+=A[i*K+k]*B[i*N+n];
            C[ci++]=s;
        }
}

// matmul_bt: args [M, K, N, addr_A, addr_B, addr_C]
void op_matmul_bt() {
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int m=0;m<M;m++)
        for(unsigned int k=0;k<K;k++){
            float s=0.0f;
            for(unsigned int n=0;n<N;n++) s+=A[m*N+n]*B[k*N+n];
            C[ci++]=s;
        }
}

// relu: args [count, addr_in, addr_out]
void op_relu() {
    unsigned int n=mem[1]; float*x=(float*)mem[2]; float*y=(float*)mem[3];
    for(unsigned int i=0;i<n;i++) y[i]=x[i]>0.0f?x[i]:0.0f;
}

// relu_bwd: args [count, addr_dy, addr_x, addr_dx]
void op_relu_bwd() {
    unsigned int n=mem[1]; float*dy=(float*)mem[2]; float*x=(float*)mem[3]; float*dx=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) dx[i]=x[i]>0.0f?dy[i]:0.0f;
}

// elem_add: args [count, addr_a, addr_b, addr_out]
void op_elem_add() {
    unsigned int n=mem[1]; float*a=(float*)mem[2]; float*b=(float*)mem[3]; float*o=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) o[i]=a[i]+b[i];
}

// sgd: args [count, addr_w, addr_g, lr_bits]
void op_sgd() {
    unsigned int n=mem[1]; float*w=(float*)mem[2]; float*g=(float*)mem[3];
    unsigned int lr_u=mem[4]; float*lr_p=(float*)&lr_u; float lr=*lr_p;
    for(unsigned int i=0;i<n;i++) w[i]-=lr*g[i];
}

// softmax: args [batch, dim, addr_in, addr_out]
void op_softmax() {
    unsigned int batch=mem[1], dim=mem[2];
    float*in=(float*)mem[3]; float*out=(float*)mem[4];
    for(unsigned int b=0;b<batch;b++){
        float*x=in+b*dim; float*y=out+b*dim;
        float mx=x[0];
        for(unsigned int i=1;i<dim;i++) if(x[i]>mx) mx=x[i];
        float s=0.0f;
        for(unsigned int i=0;i<dim;i++){
            float diff=x[i]-mx; if(diff<-10.0f) diff=-10.0f;
            float e=1.0f+diff+diff*diff*0.5f+diff*diff*diff*0.16667f+diff*diff*diff*diff*0.04167f;
            if(e<0.0f) e=0.0f; y[i]=e; s+=e;
        }
        if(s>0.0f){float is=1.0f/s; for(unsigned int i=0;i<dim;i++) y[i]*=is;}
    }
}

// rmsnorm: args [T, D, addr_x, addr_gamma, addr_y]
void op_rmsnorm() {
    unsigned int T=mem[1], D=mem[2];
    float*x=(float*)mem[3]; float*g=(float*)mem[4]; float*y=(float*)mem[5];
    for(unsigned int t=0;t<T;t++){
        float*xr=x+t*D; float*yr=y+t*D; float ss=0.0f;
        for(unsigned int d=0;d<D;d++) ss+=xr[d]*xr[d];
        float inv=1.0f, rms2=ss/(float)D+1e-6f;
        if(rms2*0.5f>0.0f){
            float x0=1.0f;
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            inv=x0;
        }
        for(unsigned int d=0;d<D;d++) yr[d]=xr[d]*inv*g[d];
    }
}

// matmul_partial: args [M, K, N, addr_A, addr_B, addr_C, col_start, col_end]
// Each core computes C[i, col_start..col_end) for all rows i
//
// FIX C12: Only primary core in each cluster (core_in_cluster==0) uses
// vectorized nmpp. Secondary cores use scalar fallback to avoid saturating
// the DDR bus with 16 concurrent nmpp calls (caused DDR controller lockup).
void op_matmul_partial() {
    int M=(int)mem[1]; int K=(int)mem[2]; int N=(int)mem[3];
    float* A=(float*)mem[4]; float* B=(float*)mem[5]; float* C=(float*)mem[6];
    unsigned int col_start=mem[7]; unsigned int col_end=mem[8];
    unsigned int actual_n = col_end - col_start;

    if (actual_n == 0) return;

    // DDR bounds sanity check
    if (col_start >= (unsigned int)N || col_end > (unsigned int)N) return;

    // Determine if this core is primary in its cluster (0,4,8,12)
    // core_in_cluster = core_index & 3
    unsigned int core_in_cluster = g_core_index & 3;

    if (core_in_cluster == 0) {
        // Primary core in cluster: use vectorized nmpp
        // B is [K, N] row-major. Column slice B[:, col_start:col_end] has stride N.
        // A: [M, K] with stride K
        // B_slice: starts at B + col_start, shape [K, actual_n] but stride = N
        // C_slice: starts at C + col_start, shape [M, actual_n] but stride = N
        nmppmMul_mm_32f(A, M, K,
                         B + col_start, K, N,
                         C + col_start, (int)actual_n, N, 0);
    } else {
        // Secondary cores: scalar fallback to reduce DDR pressure
        for (int i = 0; i < M; i++) {
            for (int j = 0; j < (int)actual_n; j++) {
                float sum = 0.0f;
                for (int k = 0; k < K; k++) {
                    sum += A[i * K + k] * B[(col_start + j) + k * N];
                }
                C[i * N + col_start + j] = sum;
            }
        }
    }
}

// Stubs for libnm6408load_nmc
extern "C" unsigned int LShift32(unsigned int a, unsigned int b) {
    unsigned int r=a; for(unsigned int i=0;i<b;i++) r<<=1; return r; }
extern "C" unsigned int RShift32(unsigned int a, unsigned int b) {
    unsigned int r=a; for(unsigned int i=0;i<b;i++) r>>=1; return r; }
extern "C" int Mul32(int a, int b) {
    int r=0,s=1; if(a<0){a=-a;s=-s;} if(b<0){b=-b;s=-s;}
    unsigned int ua=(unsigned int)a,ub=(unsigned int)b;
    while(ub){if(ub&1)r+=ua;ua<<=1;ub>>=1;} return s<0?-r:r; }

int main() {
    // ================================================================
    // FIX C11: core_index race condition
    // ================================================================
    // Host writes core_index into DDR_BASE + core*32 + 29 for each core
    // BEFORE loading the program. We read boot[29] and validate ownership
    // using a signature handshake to detect if two cores got the same index.
    volatile unsigned int* boot=(volatile unsigned int*)DDR_BASE;
    unsigned int core_index=boot[29];

    // Clamp to valid range
    if(core_index>15) core_index=0;

    // Point mem to this core's CMD block
    mem=(volatile unsigned int*)(DDR_BASE+(core_index<<5));

    // SAFETY: Write a unique signature to verify we own this cmd block
    // Each core writes 0xDEAD0000 | its_index to word 28
    mem[28] = 0xDEAD0000 | core_index;

    // Small delay to let all cores write their signatures
    for (volatile int i = 0; i < 1000; i++);

    // Verify our signature is still there (no other core overwrote it)
    if ((mem[28] & 0xFFFF) != core_index) {
        // CONFLICT DETECTED - another core has the same index!
        // Enter safe idle mode: just increment watchdog so host knows we're alive
        // but never execute any operations
        while(1) {
            mem[WATCHDOG_ADDR]++;
        }
    }

    // Store validated core index globally (used by op_matmul_partial)
    g_core_index = core_index;

    mem[STATUS_ADDR]=1; mem[WATCHDOG_ADDR]=0; mem[0]=0;
    unsigned int watchdog=0;

    // Increased watchdog timeout safety — avoid tight spin consuming DDR bandwidth
    while(1){
        watchdog++; mem[WATCHDOG_ADDR]=watchdog;
        unsigned int op=mem[0];
        if(op==OP_NOP) continue;
        if(op==OP_EXIT){mem[STATUS_ADDR]=1;mem[0]=0;break;}
        mem[STATUS_ADDR]=0;
        switch(op){
            case OP_MATMUL: op_matmul(); break; /*VEC*/
            case OP_MATMUL_AT: op_matmul_at(); break;
            case OP_MATMUL_BT: op_matmul_bt(); break;
            case OP_RELU: op_relu(); break;
            case OP_RELU_BWD: op_relu_bwd(); break;
            case OP_ELEM_ADD: op_elem_add(); break;
            case OP_SGD: op_sgd(); break;
            case OP_SOFTMAX: op_softmax(); break;
            case OP_RMSNORM: op_rmsnorm(); break;
            case OP_MATMUL_PARTIAL: op_matmul_partial(); break; /*16-CORE, DDR-SAFE*/
            default: mem[STATUS_ADDR]=2; mem[0]=0; continue;
        }
        mem[STATUS_ADDR]=1; mem[0]=0;
    }
    return 0;
}
