// ============================================================
// SUDA-Generated Dispatcher for NMC4 NeuroMatrix
// Generated by: python suda/codegen.py
// Vector matmul: nmppmMul_mm_32f (4 FPU cores, rep vlen)
// ============================================================

extern "C" {
    void nmppmMul_mm_32f(float* pSrcMtr1, int nHeight1, int nStride1,
                          float* pSrcMtr2, int nWidth1, int nStride2,
                          float* pDstMtr, int nWidth2, int nStrideDst, int bPlusDst);
}

#define DDR_BASE 0x00340000
#define CMD_BLOCK_SIZE 32
volatile unsigned int* mem;

#define OP_MATMUL               1
#define OP_MATMUL_AT            2
#define OP_MATMUL_BT            3
#define OP_RELU                 4
#define OP_RELU_BWD             5
#define OP_ELEM_ADD             10
#define OP_SGD                  20
#define OP_SOFTMAX              7
#define OP_RMSNORM              6
#define OP_MATMUL_PARTIAL       22
#define OP_NOP                  0
#define OP_EXIT                 255
#define STATUS_ADDR     30
#define WATCHDOG_ADDR   31

// matmul: args [M, K, N, addr_A, addr_B, addr_C]
// VECTORIZED via nmpp (nmppmMul_mm_32f)
void op_matmul() {
    int M=(int)mem[1]; int K=(int)mem[2]; int N=(int)mem[3];
    float* A=(float*)mem[4]; float* B=(float*)mem[5]; float* C=(float*)mem[6];
    nmppmMul_mm_32f(A, M, K, B, K, N, C, N, N, 0);
}

// matmul_at: args [M, K, N, addr_A, addr_B, addr_C]
void op_matmul_at() {
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int k=0;k<K;k++)
        for(unsigned int n=0;n<N;n++){
            float s=0.0f;
            for(unsigned int i=0;i<M;i++) s+=A[i*K+k]*B[i*N+n];
            C[ci++]=s;
        }
}

// matmul_bt: args [M, K, N, addr_A, addr_B, addr_C]
void op_matmul_bt() {
    unsigned int M=mem[1],K=mem[2],N=mem[3];
    float*A=(float*)mem[4]; float*B=(float*)mem[5]; float*C=(float*)mem[6];
    unsigned int ci=0;
    for(unsigned int m=0;m<M;m++)
        for(unsigned int k=0;k<K;k++){
            float s=0.0f;
            for(unsigned int n=0;n<N;n++) s+=A[m*N+n]*B[k*N+n];
            C[ci++]=s;
        }
}

// relu: args [count, addr_in, addr_out]
void op_relu() {
    unsigned int n=mem[1]; float*x=(float*)mem[2]; float*y=(float*)mem[3];
    for(unsigned int i=0;i<n;i++) y[i]=x[i]>0.0f?x[i]:0.0f;
}

// relu_bwd: args [count, addr_dy, addr_x, addr_dx]
void op_relu_bwd() {
    unsigned int n=mem[1]; float*dy=(float*)mem[2]; float*x=(float*)mem[3]; float*dx=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) dx[i]=x[i]>0.0f?dy[i]:0.0f;
}

// elem_add: args [count, addr_a, addr_b, addr_out]
void op_elem_add() {
    unsigned int n=mem[1]; float*a=(float*)mem[2]; float*b=(float*)mem[3]; float*o=(float*)mem[4];
    for(unsigned int i=0;i<n;i++) o[i]=a[i]+b[i];
}

// sgd: args [count, addr_w, addr_g, lr_bits]
void op_sgd() {
    unsigned int n=mem[1]; float*w=(float*)mem[2]; float*g=(float*)mem[3];
    unsigned int lr_u=mem[4]; float*lr_p=(float*)&lr_u; float lr=*lr_p;
    for(unsigned int i=0;i<n;i++) w[i]-=lr*g[i];
}

// softmax: args [batch, dim, addr_in, addr_out]
void op_softmax() {
    unsigned int batch=mem[1], dim=mem[2];
    float*in=(float*)mem[3]; float*out=(float*)mem[4];
    for(unsigned int b=0;b<batch;b++){
        float*x=in+b*dim; float*y=out+b*dim;
        float mx=x[0];
        for(unsigned int i=1;i<dim;i++) if(x[i]>mx) mx=x[i];
        float s=0.0f;
        for(unsigned int i=0;i<dim;i++){
            float diff=x[i]-mx; if(diff<-10.0f) diff=-10.0f;
            float e=1.0f+diff+diff*diff*0.5f+diff*diff*diff*0.16667f+diff*diff*diff*diff*0.04167f;
            if(e<0.0f) e=0.0f; y[i]=e; s+=e;
        }
        if(s>0.0f){float is=1.0f/s; for(unsigned int i=0;i<dim;i++) y[i]*=is;}
    }
}

// rmsnorm: args [T, D, addr_x, addr_gamma, addr_y]
void op_rmsnorm() {
    unsigned int T=mem[1], D=mem[2];
    float*x=(float*)mem[3]; float*g=(float*)mem[4]; float*y=(float*)mem[5];
    for(unsigned int t=0;t<T;t++){
        float*xr=x+t*D; float*yr=y+t*D; float ss=0.0f;
        for(unsigned int d=0;d<D;d++) ss+=xr[d]*xr[d];
        float inv=1.0f, rms2=ss/(float)D+1e-6f;
        if(rms2*0.5f>0.0f){
            float x0=1.0f;
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            x0=x0*(1.5f-0.5f*rms2*x0*x0);
            inv=x0;
        }
        for(unsigned int d=0;d<D;d++) yr[d]=xr[d]*inv*g[d];
    }
}

// matmul_partial: args [M, K, N, addr_A, addr_B, addr_C, col_start, col_end]
// Each core computes C[i, col_start..col_end) for all rows i
// Uses VECTORIZED nmpp for the column slice
void op_matmul_partial() {
    int M=(int)mem[1]; int K=(int)mem[2]; int N=(int)mem[3];
    float* A=(float*)mem[4]; float* B=(float*)mem[5]; float* C=(float*)mem[6];
    unsigned int col_start=mem[7]; unsigned int col_end=mem[8];
    unsigned int actual_n = col_end - col_start;

    if (actual_n == 0) return;

    // B is [K, N] row-major. Column slice B[:, col_start:col_end] has stride N.
    // nmppmMul_mm_32f(A, M, stride_A, B_slice, K, stride_B, C_slice, actual_n, stride_C, 0)
    // A: [M, K] with stride K
    // B_slice: starts at B + col_start, shape [K, actual_n] but stride = N (NOT actual_n!)
    // C_slice: starts at C + col_start, shape [M, actual_n] but stride = N
    nmppmMul_mm_32f(A, M, K,
                     B + col_start, K, N,
                     C + col_start, (int)actual_n, N, 0);
}

// Stubs for libnm6408load_nmc
extern "C" unsigned int LShift32(unsigned int a, unsigned int b) {
    unsigned int r=a; for(unsigned int i=0;i<b;i++) r<<=1; return r; }
extern "C" unsigned int RShift32(unsigned int a, unsigned int b) {
    unsigned int r=a; for(unsigned int i=0;i<b;i++) r>>=1; return r; }
extern "C" int Mul32(int a, int b) {
    int r=0,s=1; if(a<0){a=-a;s=-s;} if(b<0){b=-b;s=-s;}
    unsigned int ua=(unsigned int)a,ub=(unsigned int)b;
    while(ub){if(ub&1)r+=ua;ua<<=1;ub>>=1;} return s<0?-r:r; }

int main() {
    volatile unsigned int* boot=(volatile unsigned int*)DDR_BASE;
    unsigned int core_index=boot[29];
    if(core_index>15) core_index=0;
    mem=(volatile unsigned int*)(DDR_BASE+(core_index<<5));
    mem[STATUS_ADDR]=1; mem[WATCHDOG_ADDR]=0; mem[0]=0;
    unsigned int watchdog=0;
    while(1){
        watchdog++; mem[WATCHDOG_ADDR]=watchdog;
        unsigned int op=mem[0];
        if(op==OP_NOP) continue;
        if(op==OP_EXIT){mem[STATUS_ADDR]=1;mem[0]=0;break;}
        mem[STATUS_ADDR]=0;
        switch(op){
            case OP_MATMUL: op_matmul(); break; /*VEC*/
            case OP_MATMUL_AT: op_matmul_at(); break;
            case OP_MATMUL_BT: op_matmul_bt(); break;
            case OP_RELU: op_relu(); break;
            case OP_RELU_BWD: op_relu_bwd(); break;
            case OP_ELEM_ADD: op_elem_add(); break;
            case OP_SGD: op_sgd(); break;
            case OP_SOFTMAX: op_softmax(); break;
            case OP_RMSNORM: op_rmsnorm(); break;
            case OP_MATMUL_PARTIAL: op_matmul_partial(); break; /*16-CORE*/
            default: mem[STATUS_ADDR]=2; mem[0]=0; continue;
        }
        mem[STATUS_ADDR]=1; mem[0]=0;
    }
    return 0;
}
